### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by nelsonomuto** [Pocket/extension-save-to-pocket#57]
## Expected Behavior
As an outcome we need a wiki that outlines the patterns (or proposed patterns) we should use for different types of testing.

- We should outline patterns for our:
1.  unit testing 
2. functional & structural testing 
3. integration testing 
4. manual
5. cross-browser
6. performance 

## Actual Behavior
- No testing pattern(s) outlined.

## Steps to Reproduce the Problem
N/A

## Specifications
N/A

### TODO:
These are the top-level things I would expect to cover in this issue
- [x] install husky, lint-staged pre-commit hooks
- [x] configure circle ci build script
- [x] add npm test script(s)
- [x] add wiki/documentation for testing contribution guidelines 📖
- [x] setup unit (& structural) testing framework - preferably *jest*
- [x] setup storyshots 
- [ ] add cypress for integration testing

**Comment by collectedmind** [comment]
Love this and want to replicate this across all of the front end work moving forward, so we are consistent.  Let me know how if you need any support in moving this forward.

**Comment by nelsonomuto** [comment]
This would be my checklist:
- [ ] install husky, lint-staged pre-commit hooks
- [ ] configure circle ci build script
- [ ] add npm test script(s)
- [ ] add wiki/documentation for testing contribution guidelines 📖
- [ ] setup unit (& structural) testing framework - preferably *jest*
- [ ] setup storyshots 
- [ ] add cypress for integration testing

**Comment by collectedmind** [comment]
Looks great.  I think we should also be thinking about what kind of coverage we are looking to accomplish and where we should be focusing specific test types.  I want to make sure we have a priority list so we can triage appropriately and make sure tests are applied efficiently.

I would love to know more about how effective cypress will be with extensions.  Are you thinking we would test a page based version or testing the installed extension directly.

**Comment by nelsonomuto** [comment]
Documentation: https://github.com/Pocket/extension-save-to-pocket/wiki/testing

branch: https://github.com/Pocket/extension-save-to-pocket/tree/add/testingToUpdatedStructure

**Comment by collectedmind** [comment]
Closing this as the structure is out of sync after the safari/chrome integration work. Will revisit this as an actual work ticket in future.
